class UIManager {
  constructor() {
    const $=id=>document.getElementById(id);
    this.el={
      mainMenu:$('main-menu'),gameScreen:$('game-screen'),btnPlay:$('btn-play'),btnProfile:$('btn-profile'),btnSettings:$('btn-settings'),btnCredits:$('btn-credits'),btnFriends:$('btn-friends'),btnRankingRefresh:$('btn-ranking-refresh'),leaderboardPodium:$('leaderboard-podium'),leaderboardList:$('leaderboard-list'),
      menuProfileCard:$('menu-profile-card'),menuProfileAvatar:$('menu-profile-avatar'),menuProfileName:$('menu-profile-name'),menuProfileLevel:$('menu-profile-level'),menuProfileXpFill:$('menu-profile-xp-fill'),menuProfileXp:$('menu-profile-xp'),menuProfileCoins:$('menu-profile-coins'),
      accountModal:$('account-modal'),inputAccountName:$('input-account-name'),btnAccountCreate:$('btn-account-create'),accountMessage:$('account-message'),
      lobbyModal:$('lobby-modal'),lobbyHome:$('lobby-home'),lobbyRoom:$('lobby-room'),lobbySubtitle:$('lobby-subtitle'),btnLobbyClose:$('btn-lobby-close'),btnQuickPlay:$('btn-quick-play'),btnCreateRoom:$('btn-create-room'),inputRoomCode:$('input-room-code'),btnJoinRoom:$('btn-join-room'),lobbyHomeMessage:$('lobby-home-message'),lobbyCode:$('lobby-code'),btnCopyRoomCode:$('btn-copy-room-code'),lobbyMapSelect:$('lobby-map-select'),lobbyMapPreview:$('lobby-map-preview'),lobbyMapPreviewName:$('lobby-map-preview-name'),lobbyMapPreviewDesc:$('lobby-map-preview-desc'),lobbyMembers:$('lobby-members'),btnLobbyReady:$('btn-lobby-ready'),btnLobbyStart:$('btn-lobby-start'),btnLobbyLeave:$('btn-lobby-leave'),lobbyRoomMessage:$('lobby-room-message'),
      profileModal:$('profile-modal'),profileSummary:$('profile-summary'),profileFriendCode:$('profile-friend-code'),profileKills:$('profile-kills'),profileHeadshots:$('profile-headshots'),profileRevives:$('profile-revives'),profileHighestRound:$('profile-highest-round'),characterSkins:$('character-skins'),weaponSkins:$('weapon-skins'),
      settingsModal:$('settings-modal'),creditsModal:$('credits-modal'),pauseMenu:$('pause-menu'),inputPlayerName:$('input-player-name'),inputVolume:$('input-volume'),inputAimSensitivity:$('input-aim-sensitivity'),aimSensitivityValue:$('aim-sensitivity-value'),selectVfxQuality:$('select-vfx-quality'),selectHudMode:$('select-hud-mode'),inputVibration:$('input-vibration'),inputShowFps:$('input-show-fps'),btnSettingsFullscreen:$('btn-settings-fullscreen'),btnSettingsClose:$('btn-settings-close'),
      btnResume:$('btn-resume'),btnPauseSettings:$('btn-pause-settings'),btnBackToMenu:$('btn-back-to-menu'),btnPauseMobile:$('btn-pause-mobile'),
      hudHealthFill:$('hud-health-bar-fill'),hudHealthText:$('hud-health-text'),hudPlayerName:$('hud-player-name'),hudClock:$('hud-clock'),hudFps:$('hud-fps'),hudScore:$('hud-score'),hudRoom:$('hud-room'),
      hudNetworkDot:$('hud-network-dot'),hudNetworkPlayers:$('hud-network-players'),hudNetworkPing:$('hud-network-ping'),connectionLostOverlay:$('connection-lost-overlay'),
      hudKills:$('hud-kills'),hudHeadshots:$('hud-headshots'),hudRevives:$('hud-revives'),hudWeapon:$('hud-weapon'),hudAmmo:$('hud-ammo'),hudMoney:$('hud-money'),hudReload:$('hud-reload'),
      killFeed:$('kill-feed'),hudRound:$('hud-round'),hudZombies:$('hud-zombies'),roundBanner:$('round-banner'),roundBannerTitle:$('round-banner-title'),roundBannerSubtitle:$('round-banner-subtitle'),
      damageFlash:$('damage-flash-overlay'),deathScreen:$('death-screen'),deathRespawnCountdown:$('death-respawn-countdown'),btnRespawn:$('btn-respawn'),btnDeathBackToMenu:$('btn-death-back-to-menu'),spectatorStatus:$('spectator-status'),btnSpectatePrev:$('btn-spectate-prev'),btnSpectateNext:$('btn-spectate-next'),
      btnShopHud:$('btn-shop-hud'),btnMobileShop:$('btn-mobile-shop'),shopModal:$('shop-modal'),shopItems:$('shop-items'),shopMoney:$('shop-money'),shopMessage:$('shop-message'),btnShopClose:$('btn-shop-close'),
      lootPrompt:$('loot-prompt'),interactionPrompt:$('interaction-prompt'),hudZone:$('hud-zone'),hudWeaponIcon:$('hud-weapon-icon'),hudSlot1:$('hud-slot-1'),hudSlot2:$('hud-slot-2'),hudLowAmmo:$('hud-low-ammo'),
      hudRoundProgressFill:$('hud-round-progress-fill'),hudMinimap:$('hud-minimap'),hudAllies:$('hud-allies'),lowHealthVignette:$('low-health-vignette'),
      downedOverlay:$('downed-overlay'),downedTimer:$('downed-timer'),downedStatus:$('downed-status'),revivePrompt:$('revive-prompt'),revivePromptText:$('revive-prompt-text'),reviveProgressFill:$('revive-progress-fill'),btnMobileInteract:$('btn-mobile-interact'),
      scoreboardOverlay:$('scoreboard-overlay'),scoreboardRows:$('scoreboard-rows'),scoreboardRoom:$('scoreboard-room'),btnScoreboardHud:$('btn-scoreboard-hud'),btnMobileScore:$('btn-mobile-score'),
      bossOverlay:$('boss-overlay'),bossRoundText:$('boss-round-text'),btnFullscreenHud:$('btn-fullscreen-hud'),deathPenalty:$('death-penalty'),
      friendsModal:$('friends-modal'),friendsMyCode:$('friends-my-code'),btnCopyFriendCode:$('btn-copy-friend-code'),inputFriendCode:$('input-friend-code'),btnAddFriend:$('btn-add-friend'),friendsMessage:$('friends-message'),friendRequests:$('friend-requests'),friendsList:$('friends-list'),friendInviteModal:$('friend-invite-modal'),friendInviteText:$('friend-invite-text'),btnFriendInviteAccept:$('btn-friend-invite-accept'),btnFriendInviteDecline:$('btn-friend-invite-decline'),
    };
    this.settings={volume:60,showFps:false,aimSensitivity:1,vfxQuality:'auto',vibration:true,hudMode:'auto'};
    this._settingsReturnToPause=false;this._shopCatalog=null;this._shopSelf=null;this._shopBuyCallback=null;this._profileSelectCallback=null;this._loadSettings();this._bindCloseButtons();this._bindSettingsInputs();
    this.el.btnShopClose?.addEventListener('click',()=>this.hideShop());
  }

  _loadSettings(){try{const v=JSON.parse(localStorage.getItem('zso_settings_v20')||'null');if(v&&typeof v==='object')this.settings={...this.settings,...v};}catch(_){}
    if(this.el.inputVolume)this.el.inputVolume.value=this.settings.volume;if(this.el.inputShowFps)this.el.inputShowFps.checked=!!this.settings.showFps;if(this.el.inputAimSensitivity)this.el.inputAimSensitivity.value=Math.round((Number(this.settings.aimSensitivity)||1)*100);if(this.el.aimSensitivityValue)this.el.aimSensitivityValue.textContent=`${(Number(this.settings.aimSensitivity)||1).toFixed(2)}x`;if(this.el.selectVfxQuality)this.el.selectVfxQuality.value=this.settings.vfxQuality||'auto';if(this.el.selectHudMode)this.el.selectHudMode.value=this.settings.hudMode||'auto';if(this.el.inputVibration)this.el.inputVibration.checked=this.settings.vibration!==false;this.el.hudFps?.classList.toggle('hidden',!this.settings.showFps);this.applyHudMode(this.settings.hudMode||'auto');}
  _saveSettings(){try{localStorage.setItem('zso_settings_v20',JSON.stringify(this.settings));}catch(_){}window.dispatchEvent(new CustomEvent('zso:settings',{detail:{...this.settings}}));}
  _bindCloseButtons(){document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>document.getElementById(btn.getAttribute('data-close'))?.classList.add('hidden')));this.el.btnSettingsClose?.addEventListener('click',()=>this.hideSettingsModal());}
  _bindSettingsInputs(){this.el.inputVolume?.addEventListener('input',e=>{this.settings.volume=Number(e.target.value);this._saveSettings();});this.el.inputShowFps?.addEventListener('change',e=>{this.settings.showFps=e.target.checked;this.el.hudFps?.classList.toggle('hidden',!this.settings.showFps);this._saveSettings();});this.el.inputAimSensitivity?.addEventListener('input',e=>{this.settings.aimSensitivity=Number(e.target.value)/100;if(this.el.aimSensitivityValue)this.el.aimSensitivityValue.textContent=`${this.settings.aimSensitivity.toFixed(2)}x`;this._saveSettings();});this.el.selectVfxQuality?.addEventListener('change',e=>{this.settings.vfxQuality=e.target.value;this._saveSettings();});this.el.selectHudMode?.addEventListener('change',e=>{this.settings.hudMode=e.target.value;this.applyHudMode(this.settings.hudMode);this._saveSettings();});this.el.inputVibration?.addEventListener('change',e=>{this.settings.vibration=e.target.checked;this._saveSettings();});}
  applyHudMode(mode='auto'){const m=['auto','pc','mobile'].includes(mode)?mode:'auto';document.body.classList.toggle('force-mobile-ui',m==='mobile');document.body.classList.toggle('force-pc-ui',m==='pc');document.body.dataset.hudMode=m;}

  showSettingsModal(fromPause=false){this._settingsReturnToPause=!!fromPause;if(fromPause)this.hidePauseMenu();this.el.settingsModal?.classList.remove('hidden');}
  hideSettingsModal(){this.el.settingsModal?.classList.add('hidden');if(this._settingsReturnToPause){this._settingsReturnToPause=false;this.showPauseMenu();}}
  showCreditsModal(){this.el.creditsModal?.classList.remove('hidden');}
  showMainMenu(){this.el.mainMenu?.classList.remove('hidden');this.el.gameScreen?.classList.add('hidden');this.el.pauseMenu?.classList.add('hidden');this.hideShop();this.hideScoreboard();}
  showGameScreen(){this.el.mainMenu?.classList.add('hidden');this.el.gameScreen?.classList.remove('hidden');}
  showPauseMenu(){this.el.pauseMenu?.classList.remove('hidden');}
  hidePauseMenu(){this.el.pauseMenu?.classList.add('hidden');}

  showAccountModal(){this.el.accountMessage.textContent='';this.el.accountModal?.classList.remove('hidden');setTimeout(()=>this.el.inputAccountName?.focus(),50);}
  hideAccountModal(){this.el.accountModal?.classList.add('hidden');}
  setAccountMessage(text,good=false){if(this.el.accountMessage){this.el.accountMessage.textContent=text||'';this.el.accountMessage.style.color=good?'#79d77f':'#e2b76a';}}
  getAccountName(){return String(this.el.inputAccountName?.value||'').trim();}

  showLobbyHome(maps=[]){this.el.lobbyModal?.classList.remove('hidden');this.el.lobbyHome?.classList.remove('hidden');this.el.lobbyRoom?.classList.add('hidden');if(this.el.lobbySubtitle)this.el.lobbySubtitle.textContent='Escolha como jogar';this._populateMaps(maps);this.setLobbyMessage('','home');}
  showLobbyRoom(lobby,selfId){this.el.lobbyModal?.classList.remove('hidden');this.el.lobbyHome?.classList.add('hidden');this.el.lobbyRoom?.classList.remove('hidden');this.updateLobby(lobby,selfId);}
  hideLobby(){this.el.lobbyModal?.classList.add('hidden');}
  setLobbyMessage(text,where='room',good=false){const el=where==='home'?this.el.lobbyHomeMessage:this.el.lobbyRoomMessage;if(el){el.textContent=text||'';el.style.color=good?'#79d77f':'#e2b76a';}}
  _populateMaps(maps=[]){if(!this.el.lobbyMapSelect)return;if(Array.isArray(maps)&&maps.length)this._mapCatalog=maps;const list=this._mapCatalog||[];const cur=this.el.lobbyMapSelect.value;this.el.lobbyMapSelect.innerHTML='';for(const m of list){const o=document.createElement('option');o.value=m.id;o.textContent=m.name;this.el.lobbyMapSelect.appendChild(o);}if([...this.el.lobbyMapSelect.options].some(o=>o.value===cur))this.el.lobbyMapSelect.value=cur;this.previewLobbyMap(this.el.lobbyMapSelect.value||list[0]?.id||'city');}
  previewLobbyMap(mapId){const m=(this._mapCatalog||[]).find(x=>x.id===mapId);if(!m)return;if(this.el.lobbyMapPreview)this.el.lobbyMapPreview.dataset.theme=m.theme||m.id||'city';if(this.el.lobbyMapPreviewName)this.el.lobbyMapPreviewName.textContent=m.name||m.id;if(this.el.lobbyMapPreviewDesc)this.el.lobbyMapPreviewDesc.textContent=m.description||'Mapa de sobrevivência.';}
  updateLobby(lobby,selfId){if(!lobby)return;this._populateMaps(lobby.maps||[]);if(this.el.lobbyCode)this.el.lobbyCode.textContent=lobby.code||'-----';if(this.el.lobbyMapSelect){this.el.lobbyMapSelect.value=lobby.mapId||'city';this.el.lobbyMapSelect.disabled=lobby.hostId!==selfId||lobby.started===true;this.previewLobbyMap(this.el.lobbyMapSelect.value);}if(this.el.lobbySubtitle)this.el.lobbySubtitle.textContent=lobby.started?'Partida em andamento':`Sala ${lobby.code||''}`;
    if(this.el.lobbyMembers){this.el.lobbyMembers.innerHTML='';for(const m of lobby.members||[]){const row=document.createElement('div');row.className='lobby-member';const av=document.createElement('div');av.className='lobby-member-avatar';av.style.setProperty('--skin',clientCharacterSkin(m.skinId).body);const copy=document.createElement('div');const b=document.createElement('b');b.textContent=m.name+(m.isHost?' 👑':'');const sm=document.createElement('small');sm.textContent=`Nv. ${m.level||1}`;copy.append(b,sm);const st=document.createElement('span');st.className='lobby-member-status'+(m.ready?' ready':'');st.textContent=m.ready?'PRONTO':'AGUARDANDO';row.append(av,copy,st);this.el.lobbyMembers.appendChild(row);}}
    const me=(lobby.members||[]).find(m=>m.socketId===selfId);if(this.el.btnLobbyReady){this.el.btnLobbyReady.textContent=me?.ready?'NÃO PRONTO':'PRONTO';this.el.btnLobbyReady.classList.toggle('menu-btn-primary',!me?.ready);}if(this.el.btnLobbyStart){const isHost=lobby.hostId===selfId;this.el.btnLobbyStart.classList.toggle('hidden',!isHost||lobby.started);this.el.btnLobbyStart.disabled=!lobby.canStart;}
  }

  updateProfile(account,onSelect=null){if(!account)return;this._profileSelectCallback=onSelect||this._profileSelectCallback;if(this.el.inputPlayerName)this.el.inputPlayerName.value=account.name||'Sobrevivente';this.el.menuProfileCard?.classList.remove('hidden');if(this.el.menuProfileName)this.el.menuProfileName.textContent=account.name;if(this.el.menuProfileLevel)this.el.menuProfileLevel.textContent=`Nv. ${account.level||1}`;if(this.el.menuProfileXp)this.el.menuProfileXp.textContent=`${account.xpIntoLevel||0}/${account.xpForNextLevel||1} XP`;if(this.el.menuProfileCoins)this.el.menuProfileCoins.textContent=`${account.coins||0} moedas`;if(this.el.menuProfileXpFill)this.el.menuProfileXpFill.style.width=`${Math.max(0,Math.min(100,(account.xpIntoLevel||0)/Math.max(1,account.xpForNextLevel||1)*100))}%`;if(this.el.menuProfileAvatar){this.el.menuProfileAvatar.style.background=clientCharacterSkin(account.selectedSkin).body;}
    if(this.el.profileSummary)this.el.profileSummary.textContent=`${account.name} · Nv. ${account.level||1} · ${account.coins||0} moedas`;if(this.el.profileFriendCode)this.el.profileFriendCode.textContent=account.friendCode||'--------';const st=account.stats||{};if(this.el.profileKills)this.el.profileKills.textContent=st.kills||0;if(this.el.profileHeadshots)this.el.profileHeadshots.textContent=st.headshots||0;if(this.el.profileRevives)this.el.profileRevives.textContent=st.revives||0;if(this.el.profileHighestRound)this.el.profileHighestRound.textContent=st.highestRound||0;this._renderSkins(account);
  }
  _renderSkins(account){const render=(el,list,selected,type)=>{if(!el)return;el.innerHTML='';for(const s of list||[]){const card=document.createElement('button');card.type='button';card.className=`skin-card${s.unlocked?'':' locked'}${s.id===selected?' selected':''}`;const preview=document.createElement('div');preview.className=type==='character'?'skin-preview':'skin-weapon-preview';preview.style.setProperty('--skin',s.body||s.color||'#2a2a2a');const b=document.createElement('b');b.textContent=s.name;const sm=document.createElement('small');sm.textContent=s.unlocked?(s.id===selected?'EQUIPADO':'DESBLOQUEADO'):`NÍVEL ${s.level}`;card.append(preview,b,sm);if(s.unlocked)card.addEventListener('click',()=>this._profileSelectCallback?.(type,s.id));el.appendChild(card);}};render(this.el.characterSkins,account.skins,account.selectedSkin,'character');render(this.el.weaponSkins,account.weaponSkins,account.selectedWeaponSkin,'weapon');}
  showProfile(){this.el.profileModal?.classList.remove('hidden');}

  updateHealth(current,max){const m=Math.max(1,Number(max)||100),c=Math.max(0,Number(current)||0),pct=Math.max(0,Math.min(100,c/m*100));if(this.el.hudHealthFill){this.el.hudHealthFill.style.width=pct+'%';this.el.hudHealthFill.classList.toggle('low-health',pct<=30);}if(this.el.hudHealthText)this.el.hudHealthText.textContent=`${Math.round(c)}/${Math.round(m)}`;this.el.lowHealthVignette?.classList.toggle('active',pct<=30&&c>0);}
  updatePlayerName(name){if(this.el.hudPlayerName)this.el.hudPlayerName.textContent=name;}
  updateClock(sec){const m=Math.floor(sec/60).toString().padStart(2,'0'),s=Math.floor(sec%60).toString().padStart(2,'0');if(this.el.hudClock)this.el.hudClock.textContent=`${m}:${s}`;}
  updateFps(fps){if(this.settings.showFps&&this.el.hudFps)this.el.hudFps.textContent=`FPS: ${fps}`;}
  updateNetworkStatus({connected,playerCount,pingMs,roomCode}){if(this.el.hudNetworkDot){this.el.hudNetworkDot.textContent=connected?'🟢':'🔴';this.el.hudNetworkDot.classList.toggle('hud-network-dot-offline',!connected);}if(typeof playerCount==='number'&&this.el.hudNetworkPlayers)this.el.hudNetworkPlayers.textContent=`Jogadores: ${playerCount}`;if(this.el.hudNetworkPing)this.el.hudNetworkPing.textContent=pingMs==null?'Ping: --ms':`Ping: ${pingMs}ms`;if(this.el.hudRoom)this.el.hudRoom.textContent=`Sala: ${roomCode||'-----'}`;}
  showConnectionLostOverlay(){this.el.connectionLostOverlay?.classList.remove('hidden');}
  hideConnectionLostOverlay(){this.el.connectionLostOverlay?.classList.add('hidden');}

  updateCombatHud(loadout,money=0,kills=0,headshots=0,score=0){const id=loadout?.activeWeaponId||'pistol',w=clientWeapon(id);if(this.el.hudWeapon)this.el.hudWeapon.textContent=w.name.toUpperCase();if(this.el.hudWeaponIcon){this.el.hudWeaponIcon.textContent={pistol:'⌐',smg:'▰',shotgun:'═',rifle:'▱'}[id]||'⌐';this.el.hudWeaponIcon.dataset.weapon=id;}const ammo=Math.max(0,Number(loadout?.ammo)||0),reserve=Math.max(0,Number(loadout?.reserve)||0);if(this.el.hudAmmo){this.el.hudAmmo.textContent=`${ammo} / ${reserve}`;this.el.hudAmmo.classList.toggle('hud-ammo-low',ammo>0&&ammo<=Math.max(2,Math.ceil((w.magazineSize||12)*.25)));this.el.hudAmmo.classList.toggle('hud-ammo-empty',ammo===0);}this.el.hudLowAmmo?.classList.toggle('hidden',!(ammo<=Math.max(2,Math.ceil((w.magazineSize||12)*.25))));if(this.el.hudMoney)this.el.hudMoney.textContent=`$${Math.max(0,Math.round(Number(money)||0))}`;if(this.el.hudScore)this.el.hudScore.textContent=`PTS ${Math.max(0,Math.round(Number(score)||0))}`;if(this.el.hudKills)this.el.hudKills.textContent=`Kills: ${Math.max(0,Number(kills)||0)}`;if(this.el.hudHeadshots)this.el.hudHeadshots.textContent=`HS: ${Math.max(0,Number(headshots)||0)}`;if(this.el.hudRevives)this.el.hudRevives.textContent=`Revives: ${Math.max(0,Number(loadout?.revives)||0)}`;const slots=Array.isArray(loadout?.slots)?loadout.slots:[],active=Number(loadout?.activeSlot)||0;if(this.el.hudSlot1){this.el.hudSlot1.textContent=`1 · ${slots[0]?clientWeapon(slots[0]).name.toUpperCase():'—'}`;this.el.hudSlot1.classList.toggle('hud-slot-active',active===0);}if(this.el.hudSlot2){this.el.hudSlot2.textContent=`2 · ${slots[1]?clientWeapon(slots[1]).name.toUpperCase():'—'}`;this.el.hudSlot2.classList.toggle('hud-slot-active',active===1);}this.el.hudReload?.classList.toggle('hidden',!loadout?.reloading);if(this.el.shopMoney)this.el.shopMoney.textContent=`$${Math.max(0,Math.round(Number(money)||0))}`;}

  updateRoundHud(round){if(!round)return;const remaining=Number(round.zombiesRemaining??round.zombiesAlive)||0,total=Math.max(0,Number(round.zombiesTotal)||0);if(this.el.hudRound)this.el.hudRound.textContent=`Round: ${round.number}`;if(this.el.hudZombies)this.el.hudZombies.textContent=`Zumbis: ${remaining}/${total}`;if(this.el.hudRoundProgressFill){const done=total>0?Math.max(0,Math.min(1,(total-remaining)/total)):0;this.el.hudRoundProgressFill.style.width=`${Math.round(done*100)}%`;}this.setShopAvailable(round.state==='intermission');if(round.state==='countdown')this._showRoundBanner(round.bossRound?`⚠ BOSS ROUND ${round.number}`:`ROUND ${round.number}`,`COMEÇANDO EM ${round.countdownSeconds}...`);else if(round.state==='intermission')this._showRoundBanner('ROUND COMPLETO',`LOJA ABERTA · PRÓXIMO ROUND EM ${round.countdownSeconds}...`);else if(round.state==='waiting')this._showRoundBanner('AGUARDANDO JOGADORES','');else this._hideRoundBanner();}
  _showRoundBanner(t,s){this.el.roundBanner?.classList.remove('hidden');if(this.el.roundBannerTitle)this.el.roundBannerTitle.textContent=t;if(this.el.roundBannerSubtitle)this.el.roundBannerSubtitle.textContent=s;}
  _hideRoundBanner(){this.el.roundBanner?.classList.add('hidden');}

  addFeed(evt){if(!this.el.killFeed)return;const data=typeof evt==='string'?{text:evt,type:'info'}:(evt||{});const item=document.createElement('div');item.className=`kill-feed-item ${data.type||'info'}`;item.textContent=data.text||'';this.el.killFeed.prepend(item);while(this.el.killFeed.children.length>6)this.el.killFeed.lastElementChild?.remove();setTimeout(()=>{item.classList.add('fade');setTimeout(()=>item.remove(),480);},4300);}
  showKillFeed(text,headshot=false){this.addFeed({text,type:headshot?'headshot':'info'});}
  flashDamage(){if(!this.el.damageFlash)return;this.el.damageFlash.classList.remove('damage-flash-active');void this.el.damageFlash.offsetWidth;this.el.damageFlash.classList.add('damage-flash-active');}
  showBossIncoming(evt){if(!this.el.bossOverlay)return;if(this.el.bossRoundText)this.el.bossRoundText.textContent=`ROUND ${evt?.round||''}${Number(evt?.count)>1?` · ${evt.count} BOSSES`:''}`;this.el.bossOverlay.classList.remove('hidden');void this.el.bossOverlay.offsetWidth;this.el.bossOverlay.classList.add('hidden');requestAnimationFrame(()=>this.el.bossOverlay.classList.remove('hidden'));clearTimeout(this._bossTimer);this._bossTimer=setTimeout(()=>this.el.bossOverlay.classList.add('hidden'),2150);}

  updateScoreboard(rows=[],localId=null,roomCode=''){if(this.el.scoreboardRoom)this.el.scoreboardRoom.textContent=`SALA ${roomCode||'-----'}`;if(!this.el.scoreboardRows)return;this.el.scoreboardRows.innerHTML='';rows.forEach((r,i)=>{const row=document.createElement('div');row.className=`scoreboard-row${r.id===localId?' me':''}`;const rank=document.createElement('span');rank.textContent=String(i+1);const name=document.createElement('span');name.className='scoreboard-name';const dot=document.createElement('i');dot.className='scoreboard-dot';dot.style.setProperty('--skin',clientCharacterSkin(r.skinId).body);const nm=document.createElement('b');nm.textContent=r.name||'Jogador';if(r.downed)nm.className='downed';else if(r.alive===false)nm.className='dead';name.append(dot,nm);const vals=[r.score||0,r.kills||0,r.headshots||0,r.revives||0];row.append(rank,name,...vals.map(v=>{const s=document.createElement('span');s.textContent=String(v);return s;}));const ping=document.createElement('span');const p=Number(r.ping);ping.className=`scoreboard-ping ${!Number.isFinite(p)||p<100?'good':p<200?'mid':'bad'}`;ping.textContent=Number.isFinite(p)?`${Math.round(p)}ms`:'--';row.append(ping);this.el.scoreboardRows.appendChild(row);});}
  showScoreboard(){this.el.scoreboardOverlay?.classList.remove('hidden');}
  hideScoreboard(){this.el.scoreboardOverlay?.classList.add('hidden');}
  toggleScoreboard(){this.el.scoreboardOverlay?.classList.toggle('hidden');}
  updateSpectator(name){if(this.el.spectatorStatus)this.el.spectatorStatus.textContent=`ESPECTANDO: ${name||'—'}`;}

  updateLootPrompt(nearest){if(!this.el.lootPrompt)return;if(!nearest){this.el.lootPrompt.classList.add('hidden');return;}const i=nearest.item;let label=i.kind==='ammo'?'MUNIÇÃO':i.kind==='money'?`$${i.amount}`:i.kind==='medkit'?'KIT MÉDICO':clientWeapon(i.weaponId).name.toUpperCase();this.el.lootPrompt.textContent=`F / PEGAR — ${label} · ${RARITY_LABELS[i.rarity]||'Comum'}`;this.el.lootPrompt.classList.remove('hidden');}
  updateZone(zone){if(this.el.hudZone)this.el.hudZone.textContent=zone?.name||String(zone||'ZONA SELVAGEM');}
  updateAllies(remotes){if(!this.el.hudAllies)return;this.el.hudAllies.innerHTML='';for(const r of remotes.values()){const p=r?._player;if(!p)continue;const row=document.createElement('div');row.className='hud-ally';const n=document.createElement('span');n.textContent=p.name||'Aliado';const hp=document.createElement('span');hp.className=p.downed?'hud-ally-downed':p.alive===false?'hud-ally-dead':'hud-ally-health';hp.textContent=p.downed?'CAÍDO':p.alive===false?'MORTO':`${Math.max(0,Math.round(p.health||0))}HP`;row.append(n,hp);this.el.hudAllies.appendChild(row);}}
  updateInteractionPrompt(nearest,manager){if(!this.el.interactionPrompt)return;if(!nearest){this.el.interactionPrompt.classList.add('hidden');return;}const i=nearest.item,label=manager?.promptFor?.(i)||i.label||'INTERAGIR';this.el.interactionPrompt.textContent=`E / USAR — ${label}`;this.el.interactionPrompt.classList.remove('hidden');}

  showDownedScreen(){this.el.downedOverlay?.classList.remove('hidden');this.hideDeathScreen();}
  hideDownedScreen(){this.el.downedOverlay?.classList.add('hidden');}
  updateDowned(seconds,status='AGUARDE UM ALIADO'){if(this.el.downedTimer)this.el.downedTimer.textContent=`${Math.max(0,Math.ceil(Number(seconds)||0))}s`;if(this.el.downedStatus)this.el.downedStatus.textContent=status;}
  updateRevivePrompt(nearest,active){if(!this.el.revivePrompt)return;if(!nearest&&!active){this.el.revivePrompt.classList.add('hidden');if(this.el.btnMobileInteract){this.el.btnMobileInteract.firstChild.textContent='E';const sm=this.el.btnMobileInteract.querySelector('small');if(sm)sm.textContent='USAR';}return;}const name=nearest?.name||active?.targetName||'ALIADO';let pct=0,label=`SEGURE E / USAR — REVIVER ${String(name).toUpperCase()}`;if(active){pct=Math.max(0,Math.min(1,Number(active.progress)||0));label=`REVIVENDO ${String(name).toUpperCase()} · ${Math.round(pct*100)}%`;}if(this.el.revivePromptText)this.el.revivePromptText.textContent=label;if(this.el.reviveProgressFill)this.el.reviveProgressFill.style.width=`${Math.round(pct*100)}%`;this.el.revivePrompt.classList.remove('hidden');if(this.el.btnMobileInteract){this.el.btnMobileInteract.firstChild.textContent='+';const sm=this.el.btnMobileInteract.querySelector('small');if(sm)sm.textContent='REVIVER';}}

  setShopAvailable(on){this.el.btnShopHud?.classList.toggle('hidden',!on);this.el.btnMobileShop?.classList.toggle('hidden',!on);if(!on)this.hideShop();}
  showShop(catalog,self,onBuy){if(!catalog||!this.el.shopModal)return;this._shopCatalog=catalog;this._shopSelf=self;this._shopBuyCallback=onBuy;this.el.shopModal.classList.remove('hidden');this.renderShop(catalog,self);}
  hideShop(){this.el.shopModal?.classList.add('hidden');}
  isShopOpen(){return !!this.el.shopModal&&!this.el.shopModal.classList.contains('hidden');}
  updateShop(catalog,self){this._shopCatalog=catalog||this._shopCatalog;this._shopSelf=self||this._shopSelf;if(this.isShopOpen())this.renderShop(this._shopCatalog,this._shopSelf);}
  showShopMessage(text,good=false){if(!this.el.shopMessage)return;this.el.shopMessage.textContent=text||'';this.el.shopMessage.style.color=good?'#79d77f':'#e2b76a';}
  renderShop(catalog,self){if(!this.el.shopItems||!catalog)return;this.el.shopItems.innerHTML='';if(this.el.shopMoney)this.el.shopMoney.textContent=`$${Math.max(0,Number(self?.money)||0)}`;const cards=[];for(const w of catalog.weapons||[])cards.push({id:w.id,title:w.name,desc:`Arma ${RARITY_LABELS[w.rarity]||''}. Compra ocupa um dos 2 slots.`,price:w.price,rarity:w.rarity,owned:!!self?.weapons?.[w.id]});cards.push({id:'ammo',title:'Munição',desc:'Reabastece a reserva da arma atual.',price:catalog.ammo?.price||150});cards.push({id:'health',title:'Vida',desc:'Recupera sua vida até o máximo.',price:catalog.health?.price||200});const names={damage:'Dano',reload:'Recarga',movement:'Movimento'};for(const key of['damage','reload','movement']){const lvl=Number(self?.upgrades?.[key])||0,prices=catalog.upgrades?.[key]||[],max=prices.length-1;cards.push({id:`upgrade:${key}`,title:`${names[key]} ${lvl}/${max}`,desc:key==='damage'?'+10% de dano por nível':key==='reload'?'Recarga 10% mais rápida por nível':'+6% de velocidade por nível',price:lvl<max?prices[lvl+1]:0,maxed:lvl>=max});}for(const c of cards){const card=document.createElement('div');card.className=`shop-card ${c.rarity?`shop-rarity-${c.rarity}`:''}`;const title=document.createElement('div');title.className='shop-card-title';title.textContent=c.title;const desc=document.createElement('div');desc.className='shop-card-desc';desc.textContent=c.desc;const bottom=document.createElement('div');bottom.className='shop-card-bottom';const price=document.createElement('span');price.className='shop-card-price';price.textContent=c.maxed?'MÁX':c.owned?'COMPRADA':`$${c.price}`;const btn=document.createElement('button');btn.className='shop-buy-btn';btn.textContent=c.maxed?'MÁX':c.owned?'EQUIPADA':'COMPRAR';btn.disabled=!!(c.maxed||c.owned);btn.addEventListener('click',async()=>{btn.disabled=true;await this._shopBuyCallback?.(c.id);btn.disabled=false;});bottom.append(price,btn);card.append(title,desc,bottom);this.el.shopItems.appendChild(card);}}

  showFriends(){this.el.friendsModal?.classList.remove('hidden');}
  setFriendsMessage(text,good=false){if(this.el.friendsMessage){this.el.friendsMessage.textContent=text||'';this.el.friendsMessage.style.color=good?'#79d77f':'#e2b76a';}}
  updateSocial(social={},handlers={}){if(this.el.friendsMyCode)this.el.friendsMyCode.textContent=social.friendCode||'--------';
    if(this.el.friendRequests){this.el.friendRequests.innerHTML='';const req=Array.isArray(social.requests)?social.requests:[];if(!req.length)this.el.friendRequests.innerHTML='<div class="friend-empty">Nenhum pedido pendente.</div>';for(const r of req){const row=document.createElement('div');row.className='friend-row';const av=document.createElement('i');av.className='friend-avatar';av.style.setProperty('--skin',clientCharacterSkin(r.skinId).body);const copy=document.createElement('div');copy.className='friend-copy';copy.innerHTML=`<b></b><small>Nv. ${r.level||1}</small>`;copy.querySelector('b').textContent=r.name||'Jogador';const acts=document.createElement('div');acts.className='friend-actions';const ok=document.createElement('button');ok.className='mini-btn friend-accept';ok.textContent='✓';ok.onclick=()=>handlers.onRespond?.(r.id,true);const no=document.createElement('button');no.className='mini-btn';no.textContent='×';no.onclick=()=>handlers.onRespond?.(r.id,false);acts.append(ok,no);row.append(av,copy,acts);this.el.friendRequests.appendChild(row);}}
    if(this.el.friendsList){this.el.friendsList.innerHTML='';const rows=Array.isArray(social.friends)?social.friends:[];if(!rows.length)this.el.friendsList.innerHTML='<div class="friend-empty">Adicione alguém usando o código de amigo.</div>';for(const f of rows){const row=document.createElement('div');row.className='friend-row';const av=document.createElement('i');av.className='friend-avatar';av.style.setProperty('--skin',clientCharacterSkin(f.skinId).body);const copy=document.createElement('div');copy.className='friend-copy';const status={playing:'EM PARTIDA',lobby:'NO LOBBY',online:'ONLINE',offline:'OFFLINE'}[f.status]||'OFFLINE';copy.innerHTML='<b></b><small></small>';copy.querySelector('b').textContent=f.name||'Jogador';copy.querySelector('small').textContent=`Nv. ${f.level||1} · ${status}`;copy.querySelector('small').className=`friend-status ${f.status||'offline'}`;const acts=document.createElement('div');acts.className='friend-actions';const invite=document.createElement('button');invite.className='mini-btn';invite.textContent='CONVIDAR';invite.disabled=!handlers.canInvite||f.status==='offline'||f.status==='playing';invite.onclick=()=>handlers.onInvite?.(f.id);const rm=document.createElement('button');rm.className='mini-btn';rm.textContent='×';rm.title='Remover amigo';rm.onclick=()=>handlers.onRemove?.(f.id);acts.append(invite,rm);row.append(av,copy,acts);this.el.friendsList.appendChild(row);}}
  }
  renderLeaderboard(rows=[]){if(!this.el.leaderboardPodium||!this.el.leaderboardList)return;this.el.leaderboardPodium.innerHTML='';this.el.leaderboardList.innerHTML='';const top=rows.slice(0,3);for(const r of top){const card=document.createElement('div');card.className=`podium-card podium-${r.rank}`;const medal=document.createElement('span');medal.className='podium-medal';medal.textContent=r.rank===1?'🥇':r.rank===2?'🥈':'🥉';const av=document.createElement('div');av.className='podium-avatar';av.style.setProperty('--skin',clientCharacterSkin(r.skinId).body);const b=document.createElement('b');b.textContent=r.name||'Jogador';const sm=document.createElement('small');sm.textContent=`Nv. ${r.level||1} · Round ${r.stats?.highestRound||0}`;card.append(medal,av,b,sm);this.el.leaderboardPodium.appendChild(card);}for(const r of rows.slice(3,10)){const row=document.createElement('div');row.className='leaderboard-row';const rank=document.createElement('span');rank.textContent=`#${r.rank}`;const name=document.createElement('b');name.textContent=r.name||'Jogador';const lvl=document.createElement('span');lvl.textContent=`Nv. ${r.level||1}`;row.append(rank,name,lvl);this.el.leaderboardList.appendChild(row);}if(!rows.length)this.el.leaderboardList.innerHTML='<div class="friend-empty">Ranking carregando...</div>';}
  showFriendInvite(invite){if(this.el.friendInviteText)this.el.friendInviteText.textContent=`${invite?.fromName||'Um amigo'} te convidou para a sala ${invite?.roomCode||'-----'}.`;this.el.friendInviteModal?.classList.remove('hidden');}
  hideFriendInvite(){this.el.friendInviteModal?.classList.add('hidden');}
  setDeathPenalty(penalty){if(!this.el.deathPenalty)return;if(!penalty){this.el.deathPenalty.textContent='';return;}this.el.deathPenalty.innerHTML=`<b>PENALIDADE DE MORTE</b><span>-$${Math.max(0,Number(penalty.moneyLost)||0)} · -${Math.max(0,Number(penalty.scoreLost)||0)} PTS</span><small>Armas perdidas · Pistola restaurada</small>`;}

  showDeathScreen(){if(!this.el.deathScreen)return;this.el.deathScreen.classList.remove('hidden');let remaining=3;if(this.el.btnRespawn)this.el.btnRespawn.disabled=true;if(this.el.deathRespawnCountdown)this.el.deathRespawnCountdown.textContent=`Aguarde ${remaining}s...`;clearTimeout(this._deathCountdownTimer);const tick=()=>{remaining--;if(remaining<=0){if(this.el.btnRespawn)this.el.btnRespawn.disabled=false;if(this.el.deathRespawnCountdown)this.el.deathRespawnCountdown.textContent='';}else{if(this.el.deathRespawnCountdown)this.el.deathRespawnCountdown.textContent=`Aguarde ${remaining}s...`;this._deathCountdownTimer=setTimeout(tick,1000);}};this._deathCountdownTimer=setTimeout(tick,1000);}
  hideDeathScreen(){this.el.deathScreen?.classList.add('hidden');clearTimeout(this._deathCountdownTimer);}
}
